layout_spectrum: 0.06958911
typography_spectrum: 0.1234301
color:
  saturation: 0.9683801
  lightness: 0.4354211
  brandStrength: 0.4540052
  rhythmicContrast: 0.4469675
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Edge Photography
