name: Edge Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6541219
title: Photography on the edge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c2e2ee'
    - '#54553a'
    - '#a99e92'
    - '#16383b'
  brandStrength: 0.8888889
  lightness: 0.4354211
  saturation: 0.1875
  rhythmicContrast: 0.4469675
purpose: []
