name: Edge Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6541219
title: Photography on the edge
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0E0F14'
    - '#B4ACB3'
    - '#5C535C'
    - '#BD8953'
    - '#F2F1F1'
  brandStrength: 0.8888889
  lightness: 0.9232715
  saturation: 0.7318718
  rhythmicContrast: 0.8178752
purpose: []
